### ISSUE TITLE
Currently available build-container has no git installed

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish-build-maven-plugin#18]
https://github.com/eclipse-ee4j/glassfish-build-maven-plugin/blob/c612808987b5a5c913f688b442623d20779540e6/Jenkinsfile#L70-L72

It causes [Jenkins](https://ci.eclipse.org/glassfish/job/glassfishbuild-maven-plugin) jobs to fail with
```
14:36:12  [ERROR] IOException: java.io.IOException: Cannot run program "git": error=2, No such file or directory
14:36:12  [INFO] ------------------------------------------------------------------------
14:36:12  [INFO] BUILD FAILURE
14:36:12  [INFO] ------------------------------------------------------------------------
14:36:12  [INFO] Total time:  01:30 min
14:36:12  [INFO] Finished at: 2020-10-06T12:36:12Z
14:36:12  [INFO] ------------------------------------------------------------------------
14:36:12  [ERROR] Failed to execute goal org.glassfish.copyright:glassfish-copyright-maven-plugin:2.3:copyright (default) on project glassfishbuild-maven-plugin: IOException while checking copyrights: Cannot run program "git": error=2, No such file or directory -> [Help 1]
```

**Comment by pzygielo** [comment]
One way to solve it can be to install `git` in docker image - which I proposed in https://github.com/eclipse-ee4j/glassfish/pull/23224.
Another - to drop execution of glassfish-copyright-maven-plugin (which requires `git` executable).
Another - update glassfish-copyright-maven-plugin to use something like jgit instead of running external process.

**Comment by smillidge** [comment]
@hs536 can you take a look at this as I merged your change to the tini image?

**Comment by arjantijms** [comment]
>  update glassfish-copyright-maven-plugin to use something like jgit instead of running external process.

That would be an interesting update I think.
