### ISSUE TITLE
Check goals for thread safety

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish-build-maven-plugin#90]
Following goals:
- [x] `:echo`
   - https://github.com/eclipse-ee4j/glassfish-build-maven-plugin/pull/98
- [ ] `:exec`
- [ ] `:featuresets-dependencies`
- [ ] `:zip`

are used by glassfish build and cause maven to issue warning during parallel build.

Check, and if possible mark them as being `@threadSafe`.

-----

- https://github.com/eclipse-ee4j/glassfish/pull/24258

**Comment by dmatej** [comment]
I will close the issue soon:
* echo is ok
* exec was deleted in #145 
* featureset-dependencies is thread-safe as it uses dependency management and is "localized" just to a module, managed by a custom lfecycle. Also it doesn't break any [rule](https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3). However I forgot to mark it as thread-safe.
* zip was deleted in #145
